# Generated by Django 2.2.8 on 2020-03-16 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0004_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
