# Generated by Django 2.2.8 on 2020-03-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0006_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='copies',
            field=models.IntegerField(default=1),
        ),
    ]
