# Generated by Django 3.1 on 2020-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0007_contactform_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
