# Generated by Django 3.1 on 2020-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0008_workitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
