# Generated by Django 3.1 on 2020-09-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0009_workitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
