# Generated by Django 3.1 on 2020-09-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0010_workitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
