# Generated by Django 3.1 on 2020-09-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0011_auto_20200917_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
