# Generated by Django 3.1 on 2020-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0012_workitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='tech_used',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
