# Generated by Django 3.1 on 2020-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbdev', '0013_workitem_tech_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workitem',
            old_name='text',
            new_name='short_text',
        ),
        migrations.AddField(
            model_name='workitem',
            name='long_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
